spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
logging:
  level:
    com.example.app: debug
    org.hibernate.type.descriptor.sql: trace
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password:

