spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  level:
    com.example.app: debug
    org.hibernate.type.descriptor.sql: trace
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password:

